/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-02-04 03:45:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/include-nav.jsp", Long.valueOf(1612409178673L));
    _jspx_dependants.put("/WEB-INF/views/menu/./modal-menu-add.jsp", Long.valueOf(1612229904734L));
    _jspx_dependants.put("/WEB-INF/views/menu/./modal-menu-edit.jsp", Long.valueOf(1612231595770L));
    _jspx_dependants.put("/WEB-INF/include-head.jsp", Long.valueOf(1611908304464L));
    _jspx_dependants.put("/WEB-INF/views/menu/./modal-menu-confirm.jsp", Long.valueOf(1612232397164L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.3.RELEASE.jar", Long.valueOf(1612259565425L));
    _jspx_dependants.put("jar:file:/D:/JavaStudy/Code/Project/JavaProject-SCW/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/crowdfunding-admin-webui/WEB-INF/lib/spring-security-taglibs-4.2.3.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1496866852000L));
    _jspx_dependants.put("/WEB-INF/include-slidebar.jsp", Long.valueOf(1612169557377L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<base\r\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-closed {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-expanded {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"layer/layer.js\"></script>\r\n");
      out.write("<script src=\"script/docs.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".list-group-item\").click(function() {\r\n");
      out.write("\t\t\tif ($(this).find(\"ul\")) {\r\n");
      out.write("\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"tree-closed\")) {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"ztree/zTreeStyle.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台 -\r\n");
      out.write("\t\t\t\t\t控制面板</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_security_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- admin/to/loginout.html -->\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"security/to/loginout.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"查询\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t<div class=\"tree\">\r\n");
      out.write("\t\t<ul style=\"padding-left: 0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"main.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span\r\n");
      out.write("\t\t\t\t\tclass=\"badge\" style=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"admin/get/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> 用户维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"role/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-king\"></i> 角色维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"menu/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i> 菜单维护</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 实名认证审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_adv.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 广告审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_project.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 项目审核</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">7</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i> 资质维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"process.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-random\"></i> 流程管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"advertisement.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-hdd\"></i> 广告管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"message.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-comment\"></i> 消息模板</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"project_type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list\"></i> 项目分类</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"tag.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-tags\"></i> 项目标签</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"param.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i> 权限菜单列表\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float: right; cursor: pointer;\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#myModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-question-sign\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"treeDemo\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div id=\"menuAddModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">添加菜单</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t请输入节点名称：<input type=\"text\" name=\"name\" /><br />\r\n");
      out.write("\t\t\t\t\t请输入URL地址：<input type=\"text\" name=\"url\" /><br />\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-list\" />&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-dashboard\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-dashboard\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon glyphicon-tasks\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon glyphicon-tasks\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-user\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-king\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-king\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-lock\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-lock\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-ok\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-ok\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-check\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-check\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-large\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-large\" /> <br /> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-picture\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-picture\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-equalizer\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-equalizer\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-random\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-random\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-hdd\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-hdd\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-comment\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-comment\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-tags\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-tags\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list-alt\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list-alt\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"menuSaveBtn\" type=\"button\" class=\"btn btn-default\"><i class=\"glyphicon glyphicon-plus\"></i> 保存</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"menuResetBtn\" type=\"reset\" class=\"btn btn-primary\"><i class=\"glyphicon glyphicon-refresh\"></i> 重置</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div id=\"menuEditModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t请输入节点名称：<input type=\"text\" name=\"name\" /><br />\r\n");
      out.write("\t\t\t\t\t请输入URL地址：<input type=\"text\" name=\"url\" /><br />\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-list\" />&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-dashboard\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-dashboard\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon glyphicon-tasks\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon glyphicon-tasks\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-user\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-king\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-king\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-lock\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-lock\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-ok\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-ok\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-check\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-check\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-large\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-large\" /> <br /> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-picture\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-picture\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-equalizer\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-equalizer\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-random\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-random\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-hdd\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-hdd\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-comment\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-comment\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-tags\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-tags\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list-alt\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list-alt\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"menuEditBtn\" type=\"button\" class=\"btn btn-default\"><i class=\"glyphicon glyphicon-edit\"></i> 更新</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div id=\"menuConfirmModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t您真的要删除<span id=\"removeNodeSpan\"></span>这个节点吗？\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"confirmBtn\" type=\"button\" class=\"btn btn-danger\"><i class=\"glyphicon glyphicon-ok\"></i> OK</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<script src=\"ztree/jquery.ztree.all-3.5.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"crowd/menu-page.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tinitTreeNode();\r\n");
      out.write("\t\t\t$(\"#treeDemo\").on(\"click\", \".add\", function() {\r\n");
      out.write("\t\t\t\t//console.log(11111);\r\n");
      out.write("\t\t\t\twindow.pid = $(this).attr(\"dataid\");\r\n");
      out.write("\t\t\t\t$(\"#menuAddModal\").modal(\"show\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$(\"#treeDemo\").on(\"click\", \".edit\", function() {\r\n");
      out.write("\t\t\t\t//console.log(11111);\r\n");
      out.write("\t\t\t\twindow.id = $(this).attr(\"dataid\");\r\n");
      out.write("\t\t\t\t$(\"#menuEditModal\").modal(\"show\");\r\n");
      out.write("\t\t\t\t//获取zTreeObj对象\r\n");
      out.write("\t\t\t\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"treeDemo\");\r\n");
      out.write("\t\t\t\t//获取节点对象\r\n");
      out.write("\t\t\t\tvar key = \"id\";\r\n");
      out.write("\t\t\t\tvar value = window.id;\r\n");
      out.write("\t\t\t\tvar currentNode = zTreeObj.getNodeByParam(key, value);\r\n");
      out.write("\t\t\t\tconsole.log(currentNode);\r\n");
      out.write("\t\t\t\t//回显表单数据\r\n");
      out.write("\t\t\t\t$(\"#menuEditModal [name=name]\").val(currentNode.name);\r\n");
      out.write("\t\t\t\t$(\"#menuEditModal [name=url]\").val(currentNode.url);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#menuEditModal [name=icon]\").val([ currentNode.icon ]);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#treeDemo\").on(\"click\", \".remove\", function() {\r\n");
      out.write("\t\t\t\twindow.id = $(this).attr(\"dataid\");\r\n");
      out.write("\t\t\t\t$(\"#menuConfirmModal\").modal(\"show\");\r\n");
      out.write("\t\t\t\t//获取zTreeObj对象\r\n");
      out.write("\t\t\t\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"treeDemo\");\r\n");
      out.write("\t\t\t\t//获取节点对象\r\n");
      out.write("\t\t\t\tvar key = \"id\";\r\n");
      out.write("\t\t\t\tvar value = window.id;\r\n");
      out.write("\t\t\t\tvar currentNode = zTreeObj.getNodeByParam(key, value);\r\n");
      out.write("\t\t\t\t$(\"#removeNodeSpan\").html(\"<i class='\"+currentNode.icon+\"'></i>\"+currentNode.name);\r\n");
      out.write("\t\t\t\t//回显表单数据\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$(\"#confirmBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar postData = {\r\n");
      out.write("\t\t\t\t\tid : window.id\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"menu/delete.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : postData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\tvar result = res.result;\r\n");
      out.write("\t\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t\tinitTreeNode();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"删除失败！\" + res.message);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#menuConfirmModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#menuEditBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar name = $.trim($(\"#menuEditModal [name=name]\").val());\r\n");
      out.write("\t\t\t\tvar url = $.trim($(\"#menuEditModal [name=url]\").val());\r\n");
      out.write("\t\t\t\t//选中的icon\r\n");
      out.write("\t\t\t\tvar icon = $(\"#menuEditModal [name=icon]:checked\").val();\r\n");
      out.write("\t\t\t\tvar postData = {\r\n");
      out.write("\t\t\t\t\tid : window.id,\r\n");
      out.write("\t\t\t\t\tname : name,\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\ticon : icon\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif (postData.name == \"\" || postData.url == \"\") {\r\n");
      out.write("\t\t\t\t\tlayer.msg(\"名称或url为空，请重新输入！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"menu/update.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : postData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\tvar result = res.result;\r\n");
      out.write("\t\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t\t\tinitTreeNode();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"保存失败！\" + res.message);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#menuEditModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#menuSaveBtn\").click(function() {\r\n");
      out.write("\t\t\t\tvar name = $.trim($(\"#menuAddModal [name=name]\").val());\r\n");
      out.write("\t\t\t\tvar url = $.trim($(\"#menuAddModal [name=url]\").val());\r\n");
      out.write("\t\t\t\t//选中的icon\r\n");
      out.write("\t\t\t\tvar icon = $(\"#menuAddModal [name=icon]:checked\").val();\r\n");
      out.write("\t\t\t\tvar postData = {\r\n");
      out.write("\t\t\t\t\tpid : window.pid,\r\n");
      out.write("\t\t\t\t\tname : name,\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\ticon : icon\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif (postData.name == \"\" || postData.url == \"\") {\r\n");
      out.write("\t\t\t\t\tlayer.msg(\"名称或url为空，请重新输入！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"menu/save.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : postData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\tvar result = res.result;\r\n");
      out.write("\t\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t\t\tinitTreeNode();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"保存失败！\" + res.message);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#menuAddModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t$(\"#menuResetBtn\").click();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_security_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f0.setParent(null);
      // /WEB-INF/include-nav.jsp(20,8) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f0.setProperty("principal.originalAdmin.userName");
      int _jspx_eval_security_005fauthentication_005f0 = _jspx_th_security_005fauthentication_005f0.doStartTag();
      if (_jspx_th_security_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f0);
      _jspx_th_security_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f0_reused);
    }
    return false;
  }
}
