server:
  port: 8001
  
spring:
  application:
    name: ceking-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka   

ribbon:
  read-time-out: 10000
  connect-time-out: 10000
  