/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-02-01 08:39:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class role_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/include-nav.jsp", Long.valueOf(1611900981429L));
    _jspx_dependants.put("/WEB-INF/include-head.jsp", Long.valueOf(1611908304464L));
    _jspx_dependants.put("/WEB-INF/include-slidebar.jsp", Long.valueOf(1612150174852L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<base\r\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-closed {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-expanded {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"layer/layer.js\"></script>\r\n");
      out.write("<script src=\"script/docs.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".list-group-item\").click(function() {\r\n");
      out.write("\t\t\tif ($(this).find(\"ul\")) {\r\n");
      out.write("\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"tree-closed\")) {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pagination.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery.pagination.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台 -\r\n");
      out.write("\t\t\t\t\t控制面板</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginAdmin.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"admin/to/loginout.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"查询\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t<div class=\"tree\">\r\n");
      out.write("\t\t<ul style=\"padding-left: 0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"main.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span\r\n");
      out.write("\t\t\t\t\tclass=\"badge\" style=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"admin/get/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> 用户维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"role/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-king\"></i> 角色维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"permission.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i> 菜单维护</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 实名认证审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_adv.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 广告审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_project.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 项目审核</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">7</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i> 资质维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"process.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-random\"></i> 流程管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"advertisement.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-hdd\"></i> 广告管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"message.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-comment\"></i> 消息模板</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"project_type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list\"></i> 项目分类</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"tag.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-tags\"></i> 项目标签</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"param.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th\"></i> 数据列表\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\" role=\"form\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control has-success\" id=\"keyWord\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"请输入查询条件\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"btnSearch\" class=\"btn btn-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i> 查询\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" id=\"batchRemove\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\" glyphicon glyphicon-remove\"></i> 删除\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"showAddModel\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 新增\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table  table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\"><input type=\"checkbox\" id=\"chkAll\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"100\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"rolePageBody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"Pagination\" class=\"pagination\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span><span class=\"sr-only\">Close</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">新增角色</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"roleId\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleInputPassword1\">角色名称</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"roleName\" placeholder=\"请输入角色名称\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"btnSave\" class=\"btn btn-success\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 保存\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"reset\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-refresh\"></i> 重置\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"crowd/role-page.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\twindow.pageNum = 1;\r\n");
      out.write("\t\t\twindow.pageSize = 5;\r\n");
      out.write("\t\t\twindow.keyWord = \"\";\r\n");
      out.write("\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t$(\"#btnSearch\").click(function() {\r\n");
      out.write("\t\t\t\tvar keyWord = $(\"#keyWord\").val();\r\n");
      out.write("\t\t\t\twindow.keyWord = keyWord;\r\n");
      out.write("\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$(\"#showAddModel\").click(function() {\r\n");
      out.write("\t\t\t\t$(\"#myModalLabel\").html(\"新增角色\");\r\n");
      out.write("\t\t\t\t$(\"#myModal\").modal(\"show\");\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$(\"#btnSave\").click(function() {\r\n");
      out.write("\t\t\t\tvar postData = {\r\n");
      out.write("\t\t\t\t\tid : $(\"#roleId\").val(),\r\n");
      out.write("\t\t\t\t\tname : $(\"#roleName\").val()\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif (postData.id == \"\") {\r\n");
      out.write("\t\t\t\t\t//新增\r\n");
      out.write("\t\t\t\t\tpostData.id = 0;\r\n");
      out.write("\t\t\t\t\twindow.pageNum = 99999;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"role/save.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : postData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\tif (result.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"保存成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\t//console.log(err);\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#myModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t//清理模态框\r\n");
      out.write("\t\t\t\t$(\"#roleName\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#roleId\").val(\"\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#chkAll\").click(function(){\r\n");
      out.write("\t\t\t\tvar status = this.checked;\r\n");
      out.write("\t\t\t\t$(\".btn-chk-role\").prop(\"checked\",status);\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\".btn-chk-role\").click(function(){\r\n");
      out.write("\t\t\t\t//已选中的数量\r\n");
      out.write("\t\t\t\tvar chkBoxCount = $(\".btn-chk-role:checked\").length;\r\n");
      out.write("\t\t\t\t//全部的数量\r\n");
      out.write("\t\t\t\tvar totalChkBoxCount = $(\".btn-chk-role\").length;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#chkAll\").prop(\"checked\",(chkBoxCount==totalChkBoxCount?true:false));\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#batchRemove\").click(function(){\r\n");
      out.write("\t\t\t\tvar ids=\"\";\r\n");
      out.write("\t\t\t\tvar roleArray=[];\r\n");
      out.write("\t\t\t\t$(\".btn-chk-role\").each(function(){\r\n");
      out.write("\t\t\t\t\tif(this.checked){\r\n");
      out.write("\t\t\t\t\t\t//var name = this.dataName;\r\n");
      out.write("\t\t\t\t\t\tvar id = $(this).attr(\"dataId\");\r\n");
      out.write("\t\t\t\t\t\troleArray.push(id);\r\n");
      out.write("\t\t\t\t\t\t/* roleArray.push({\r\n");
      out.write("\t\t\t\t\t\t\tid:id,\r\n");
      out.write("\t\t\t\t\t\t\tname:name\r\n");
      out.write("\t\t\t\t\t\t}); */\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tif(roleArray.length==0){\r\n");
      out.write("\t\t\t\t\tlayer.msg(\"请选择要删除的角色！\");\r\n");
      out.write("\t\t\t\t\treturn ;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar postData = JSON.stringify(roleArray);\r\n");
      out.write("\t\t\t\tconsole.log(postData)\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"role/deleteBatch.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata :postData,\r\n");
      out.write("\t\t\t\t\tcontentType:\"application/json;charset=UTF-8\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\tif (result.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tconsole.log(ids);\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tfunction editRole(id, name) {\r\n");
      out.write("\t\t\t$(\"#roleId\").val(id);\r\n");
      out.write("\t\t\t$(\"#roleName\").val(name);\r\n");
      out.write("\t\t\t$(\"#myModalLabel\").html(\"编辑角色\");\r\n");
      out.write("\t\t\t$(\"#myModal\").modal(\"show\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction delRole(id, name) {\r\n");
      out.write("\t\t\tvar postData = {\r\n");
      out.write("\t\t\t\tid : id\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tlayer.confirm('确定要删除角色【' + name + '】吗？', {\r\n");
      out.write("\t\t\t\ticon : 3,\r\n");
      out.write("\t\t\t\ttitle : '提示'\r\n");
      out.write("\t\t\t}, function(index) {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"role/delete.json\",\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdata : postData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\t\tif (result.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\tlayer.msg(\"删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(err) {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(err);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tlayer.close(index);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
